# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 0, 561, 71))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 551, 41))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.privacy_policy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.privacy_policy_btn.setGeometry(QtCore.QRect(30, 120, 411, 41))
        self.privacy_policy_btn.setStyleSheet("QPushButton {\n"
"background-color: rgb(71, 118, 93);\n"
"color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"font: 57 14pt \"IBM Plex Sans\";\n"
"}")
        self.privacy_policy_btn.setAutoDefault(False)
        self.privacy_policy_btn.setObjectName("privacy_policy_btn")
        self.path_le = QtWidgets.QLineEdit(self.centralwidget)
        self.path_le.setGeometry(QtCore.QRect(180, 190, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.path_le.setFont(font)
        self.path_le.setText("")
        self.path_le.setObjectName("path_le")
        self.change_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_path_btn.setGeometry(QtCore.QRect(520, 190, 151, 41))
        self.change_path_btn.setStyleSheet("QPushButton {\n"
"background-color: rgb(71, 118, 93);\n"
"color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"font: 57 14pt \"IBM Plex Sans\";\n"
"}")
        self.change_path_btn.setAutoDefault(False)
        self.change_path_btn.setObjectName("change_path_btn")
        self.install_btn = QtWidgets.QPushButton(self.centralwidget)
        self.install_btn.setGeometry(QtCore.QRect(30, 260, 151, 41))
        self.install_btn.setStyleSheet("QPushButton {\n"
"background-color: rgb(71, 118, 93);\n"
"color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"font: 57 14pt \"IBM Plex Sans\";\n"
"}")
        self.install_btn.setAutoDefault(False)
        self.install_btn.setObjectName("install_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.state_name = QtWidgets.QLabel(self.centralwidget)
        self.state_name.setGeometry(QtCore.QRect(30, 320, 391, 51))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(14)
        self.state_name.setFont(font)
        self.state_name.setText("")
        self.state_name.setObjectName("state_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AREA - Install"))
        self.label.setText(_translate("MainWindow", "Установщик AREA - Student"))
        self.label_2.setText(_translate("MainWindow", "Перед установкой прочтите политику конфиденциальности"))
        self.privacy_policy_btn.setText(_translate("MainWindow", "Открыть политику конфиденциальности"))
        self.change_path_btn.setText(_translate("MainWindow", "Выбрать путь"))
        self.install_btn.setText(_translate("MainWindow", "Установить"))
        self.label_3.setText(_translate("MainWindow", "Путь установки"))
